version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_PASS}"
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE="${DB_NAME}"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
volumes:
 mysql: