version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '${PMA_PORT}:80'
volumes:
 mysql: